site_name: Jacob Jenkins Books
site_description: "Jacob's 手摸手Jenkins实用教程"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2016-2020 Jacob Xi"

plugins:
  - search # necessary for search to work
  - awesome-pages
nav:
  - 'Welcome': "index.md"
  - '一、Jenkins 运维管理':
    - '第一节 Jenkins 运维管理' : 'jk_chapter1.md'
    - '第二节 分布式构建与并行构建' : 'jk_chapter1_2.md'
    - '第三节 可视化构建试图' : 'jk_chapter1_3.md'
  - '二、Jenkins 流水线基础':
    - '第一节 编写 Jenkinsfile 运行流水线' : 'chap2/1chap2_Jenkinsfile.md'
    - '第二节 声明式流水线语法' : 'chap2/2chap2_declarative_pipeline.md'
    - '第三节 脚本化Pipeline' : 'chap2/3chap2_script_pipeline.md'
    - '第四节 Pipeline 扩展——共享库' : 'chap2/4chap2_sharedlib.md'
    - '第五节 如何快速上手Jenkinsfile编写' : 'chap2/5chap2_quick_jenkinsfile.md'
    - '第六节 脚本式管道与声明式管道-四个实际差异' : 'chap2/6chap2_pipe_vs_dec.md'
    - '第七节 使用Jenkins Git参数实现分支标签动态选择' : 'chap2/7chap2_jenkins_git.md'
  - '三、Groovy 基础':
    - '第一节 Groovy 简明教程' : 'chap3/1chap3_groovy_basic.md'
    - '第二节 Groovy 基础' : 'chap3/2chap3_groovy_basic2.md'
  - '四、构建工具集成':
    - '第一节 构建工具集成' : 'chap4/1chp4_tools1.md'
    - '第二节 集成 SaltStack 部署工具': 'chap4/2chp4_tools2.md'
    - '第三节 Jenkins集成Ansibe实现自动化部署' : 'chap4/3chp4_tools3.md'
    - '第四节 Jenkins集成Ansibe实战手册 - BB Mobile（2018）' : 'chap4/4chp4_tools4.md'
  - '五、凭证管理':
    - '第一节 凭证管理' : 'chap5/1chap5_cred1.md'
    - '第二节 凭证管理使用HashiCorp Vault' : 'chap5/2chap5_vault.md'
    - '第二节(Extra) - Store Secrets using Hashicorp Vault with Docker' : 'chap5/3docker_valut.md'
    - '第三节 在Jenkins日志中隐藏敏感信息' : 'chap5/4docker_mask.md'
  - '六、用户认证集成':
    - '第一节 Ldap 用户认证集成' : 'chap6/1chap6_ldap.md'
    - '第二节 Jenkins集成 Gitlab SSO 单点登录' : 'chap6/2chap6_gitlab.md'
    - '第三节 Jenkins集成 Github SSO 单点登录' : 'chap6/3chap6_github.md'
  - '七、Gitlab 版本控制系统集成':
    - '第一节 Gitlab – Jenkins Integration' : 'chap7/1chap7_gitlab_connect.md'
    - '第二节 Gitlab-Jenkins 版本控制' : 'chap7/2chap7_gitlab_pipeline.md'
    - '第三节 Gitlab-Jenkins 版本控制（补充）' : 'chap7/3chap7_gitlab_pipeline_extra.md'
  - '八、代码质量平台集成': 
    - '第一节 代码质量' : 'chap8/1chap8_code_quality.md'
    - '第二节 SonarQube：持续代码质量检查' : 'chap8/2chap8_code_quality_sonarqube.md'
    - '第三节 Allure测试报告：更美观的测试报告' : 'chap8/3chap8_code_quality_allure.md'
    - '第四季 代码质量平台集成(SonarQube Final Edition)' : 'chap8/4chap8_code_quality_integration.md'
  - '九、制品库集成': 
    - '第一节 Sonatype Nexus 基本介绍与安装' : 'chap9/chap9_artifact0.md'
    - '第二节 制品管理' : 'chap9/chap9_artifact1.md'
    - '第三节 Nexus 制品上传' : 'chap9/chap9_artifact2.md'
    - '第四节 Jenkins & Jfrog Artifactory' : 'chap9/chap9_artifact3.md'
  - '十、需求管理工具集成': 
    - '第一节 k8s 安装本地 Jira 服务' : 'chap10/1chap10_jira_install.md'
    - '第二节 Jenkins 配置端到端流水线（Jira和Gitlab的集成）' : 'chap10/2chap10_jira_gilab.md'
  - '十一、Docker 集成':
    - '第一节 基于 Docker 配置构建资源池' : 'chap11/1Docker_agents.md'
    - '第二节 基于Docker的pipeline流水线' : 'chap11/2Docker_pipeline.md'
    - '第三节 构建应用镜像到镜像仓库管理' : 'chap11/3Docker_registry.md'
    - '第四节 使用Groovy代码初始化Docker配置' : 'chap11/4Docker_groovy.md'
  - '十二、K8S 平台集成':
    - 'K8S 平台集成(全)' : 'chap12/1k8s_install.md'
    - '使用 Jenkins Pipeline 流水线部署 Kubernetes 应用': 'chap12/2K8s_pipeline.md'
  - '十三、自动化接口测试':
    - '第一节 Jmeter & Ant 自动化测试' : 'chap13/1jmeter.md'
    - '第二节 Jenkins、Ant、Jmeter 自动化测试' : 'chap13/2jenkins_jmeter.md'
  - '十四、流水线最佳实践':
    - '第一节 基于Jira端到端流水线的最佳实践': 'chap14/1JIRA_JEN_K8S.md'
    - '第二节 Jenkins K8S Gitlab 集成': 'chap14/2JEN_K8S_API.md'
    - '第三节 Jenkins + K8S + Gitlab 构建 RLEASE 打包发布更新流水线到K8S集群': 'chap14/3Jen_k8s_pipeline.md'
    - '第四节 版本晋级及发布流水线' : 'chap14/4Jen_update_deploy_pip.md'
    - '第五节 前端后端项目发布流水线（Java+Nodejs)' : 'chap14/5back_front_pipeline.md'
  - '十五、监控与API调用':
    - '第一节 使用 Prometheus 监控 Jenkins' : 'chap15/1Jenkins_Prometheus.md'
    - '第二节 Jenkins+InfluxDB+Grafana 收集构建数据' : 'chap15/2Jenkins_InfluxDB_Grafana.md'
    - '第三节 Jenkins Python API 实践' : 'chap15/3Jenkins_python_API.md'
    - '第四节 Jenkins REST API 使用实践' : 'chap15/4Jenkins_REST_API.md'
    - '第五节 Jenkins Core Api & Job DSL创建项目' : 'chap15/5Jenkins_DSL.md'
  - '十六、持续交付理论分析':
    - 'L1 量身定制你的持续交付体系': 'chap16/1cd_intro.md'
    - 'L2 配置管理': 'chap16/2config_mgt.md'
    - 'L3 环境管理': 'chap16/3Env_mgt.md'
  - 'Extra 知识扩展':
    - 'GitHub+Travis+Mkdocs自动化构建文档库' : 'Mkdocs_github_travis.md'
 

repo_url: https://github.com/Chao-Xi/jxjenkinsbook.git
repo_name: "jxjenkinsbook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  i18n:
    prev: 'Previous'
    next: 'Next'



