site_name: Jacob Jenkins Books
site_description: "Jacob's 手摸手Jenkins实用教程"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2016-2020 Jacob Xi"

plugins:
  - search # necessary for search to work
  - awesome-pages
nav:
  - 'Welcome': "index.md"
  - '一、Jenkins 运维管理':
    - '第一节 Jenkins 运维管理' : 'jk_chapter1.md'
    - '第二节 分布式构建与并行构建' : 'jk_chapter1_2.md'
    - '第三节 可视化构建试图' : 'jk_chapter1_3.md'
  - '二、Jenkins 流水线基础':
    - '第一节 编写 Jenkinsfile 运行流水线' : 'chap2/1chap2_Jenkinsfile.md'
    - '第二节 声明式流水线语法' : 'chap2/2chap2_declarative_pipeline.md'
    - '第三节 脚本化Pipeline' : 'chap2/3chap2_script_pipeline.md'
    - '第四节 Pipeline 扩展——共享库' : 'chap2/4chap2_sharedlib.md'
    - '第五节 如何快速上手Jenkinsfile编写' : 'chap2/5chap2_quick_jenkinsfile.md'
    - '第六节 脚本式管道与声明式管道-四个实际差异' : 'chap2/6chap2_pipe_vs_dec.md'
    - '第七节 使用Jenkins Git参数实现分支标签动态选择' : 'chap2/7chap2_jenkins_git.md'
  - '三、Groovy 基础':
    - '第一节 Groovy 简明教程' : 'chap3/1chap3_groovy_basic.md'
    - '第二节 Groovy 基础' : 'chap3/2chap3_groovy_basic2.md'
  - '四、构建工具集成':
    - '第一节 构建工具集成' : 'chap4/1chp4_tools1.md'
    - '第二节 集成 SaltStack 部署工具': 'chap4/2chp4_tools2.md'
    - '第三节 Jenkins集成Ansibe实现自动化部署' : 'chap4/3chp4_tools3.md'
    - '第四节 Jenkins集成Ansibe实战手册 - BB Mobile（2018）' : 'chap4/4chp4_tools4.md'
  - '五、凭证管理':
    - '第一节 凭证管理' : 'chap5/1chap5_cred1.md'
    - '第二节 凭证管理使用HashiCorp Vault' : 'chap5/2chap5_vault.md'
    - '第二节(Extra) - Store Secrets using Hashicorp Vault with Docker' : 'chap5/3docker_valut.md'
    - '第三节 在Jenkins日志中隐藏敏感信息' : 'chap5/4docker_mask.md'
  - '六、用户认证集成':
    - '第一节 Ldap 用户认证集成' : 'chap6/1chap6_ldap.md'
    - '第二节 Jenkins集成 Gitlab SSO 单点登录' : 'chap6/2chap6_gitlab.md'
    - '第三节 Jenkins集成 Github SSO 单点登录' : 'chap6/3chap6_github.md'
  - '七、Gitlab 版本控制系统集成':
    - '第一节 Gitlab – Jenkins Integration' : 'chap7/1chap7_gitlab_connect.md'
    - '第二节 Gitlab-Jenkins 版本控制' : 'chap7/2chap7_gitlab_pipeline.md'
    - '第三节 Gitlab-Jenkins 版本控制（补充）' : 'chap7/3chap7_gitlab_pipeline_extra.md'
  - 'Extra 知识扩展':
    - 'GitHub+Travis+Mkdocs自动化构建文档库' : 'Mkdocs_github_travis.md'
 

repo_url: https://github.com/Chao-Xi/jxjenkinsbook.git
repo_name: "jxjenkinsbook"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  i18n:
    prev: 'Previous'
    next: 'Next'



